name: Setup
description: Setup Bun and install packages

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install packages
      shell: bash
      run: bun install

    - name: Check Branch
      shell: bash
      run: |
        if [[ "${{ github.event.pull_request.head.ref }}" == "changeset-release/main" ]]; then
          echo "Bypassing checks for changeset-release/main"
          exit 0
        fi
